// Krishna's Aura product catalog.
// Standard Sivakasi-style cracker categories and product types. Used as
// demo-mode data and as the one-time seed for the Firestore `products`
// collection (seller dashboard has a "Seed catalog" button).

export const CATEGORIES = [
  "Single Sound Crackers",
  "Bijili Crackers",
  "Deluxe Crackers",
  "Bomb Crackers",
  "Festival Crackers",
  "Flower Pots",
  "Mud Pots",
  "Ground Chakkers",
  "Twinkling Star",
  "Rockets",
  "Multicolour Shots",
  "Fancy Pipes",
  "Pencil Celebration",
  "Kids Special",
  "Color Matches",
  "Sparklers",
  "Gift Boxes",
  "New Arrivals",
];

let n = 0;
const P = (name, category, unit, price, dPct = 20) => ({
  id: `seed-${++n}`,
  name,
  category,
  unit,
  price,
  discount: Math.round(price * (dPct / 100)),
  finalPrice: price - Math.round(price * (dPct / 100)),
  imageUrl: "",
});

export const SEED_PRODUCTS = [
  // Single Sound Crackers
  P('2¾" Kuruvi', "Single Sound Crackers", "1 Pkt", 35),
  P('3½" Lakshmi', "Single Sound Crackers", "1 Pkt", 80),
  P('4" Hulk', "Single Sound Crackers", "1 Pkt", 90),
  P('4" Delux Lakshmi', "Single Sound Crackers", "1 Pkt", 150),
  P('4½" Gold Lakshmi', "Single Sound Crackers", "1 Pkt", 160),
  P('5" Bagupali', "Single Sound Crackers", "1 Pkt", 275),
  P('6" Joker', "Single Sound Crackers", "1 Pkt", 300),
  // Bijili
  P("Red Bijili (50 Pcs)", "Bijili Crackers", "1 Pkt", 110),
  P("Red Bijili (100 Pcs)", "Bijili Crackers", "1 Pkt", 175),
  P("Striped Bijili (50 Pcs)", "Bijili Crackers", "1 Pkt", 120),
  P("Striped Bijili (100 Pcs)", "Bijili Crackers", "1 Pkt", 190),
  // Deluxe
  P("24 Delux Crackers", "Deluxe Crackers", "1 Pkt", 250),
  P("50 Delux Crackers", "Deluxe Crackers", "1 Pkt", 500),
  P("100 Delux Crackers", "Deluxe Crackers", "1 Pkt", 1000),
  // Bomb
  P("Auto Bomb", "Bomb Crackers", "1 Box", 225),
  P("Hydro Bomb", "Bomb Crackers", "1 Box", 325),
  P("Classic Bomb", "Bomb Crackers", "1 Box", 550),
  P("7 Ply Bomb", "Bomb Crackers", "1 Box", 850),
  P("12 Ply Bomb", "Bomb Crackers", "1 Box", 1250),
  // Festival
  P("1 Hrz Sound", "Festival Crackers", "1 Box", 750),
  P("2 Hrz Sound", "Festival Crackers", "1 Box", 1500),
  P("5 Hrz Sound", "Festival Crackers", "1 Box", 3750),
  P("10 Hrz Sound", "Festival Crackers", "1 Box", 7500),
  P("1/4 Kg Paper Bomb", "Festival Crackers", "1 Box", 250),
  P("1/4 Kg Color Bomb", "Festival Crackers", "1 Box", 325),
  P("1/2 Kg Paper Bomb", "Festival Crackers", "1 Box", 500),
  P("1 Kg Paper Bomb", "Festival Crackers", "1 Box", 1000),
  // Flower Pots
  P("Flower Pots Big", "Flower Pots", "1 Box", 290),
  P("Flower Pots Special", "Flower Pots", "1 Box", 345),
  P("Flower Pots Asoka", "Flower Pots", "1 Box", 425),
  P("Flower Pots Color Koti", "Flower Pots", "1 Box", 875),
  P("Flower Pots Deluxe (5 Pcs)", "Flower Pots", "1 Box", 750),
  P("Flower Pots Deluxe (10 Pcs)", "Flower Pots", "1 Box", 1475),
  P("Monster Box (10 Pcs)", "Flower Pots", "1 Box", 2150),
  // Mud Pots
  P("Mutt Pot", "Mud Pots", "1 Box", 1700),
  P("OMG Pots", "Mud Pots", "1 Box", 2250),
  // Ground Chakkers
  P("Ground Chakkers Big (10 Pcs)", "Ground Chakkers", "1 Box", 185),
  P("Ground Chakkers Big (25 Pcs)", "Ground Chakkers", "1 Box", 460),
  P("Ground Chakkers Special", "Ground Chakkers", "1 Box", 340),
  P("Ground Chakkers Deluxe", "Ground Chakkers", "1 Box", 575),
  P("Spinner Special", "Ground Chakkers", "1 Box", 550),
  P("Spinner Deluxe", "Ground Chakkers", "1 Box", 650),
  P("Wire Chakker", "Ground Chakkers", "1 Box", 750),
  // Twinkling Star
  P('1½" Twinkling Star', "Twinkling Star", "1 Box", 120),
  P('4" Twinkling Star', "Twinkling Star", "1 Box", 350),
  // Rockets
  P("Rocket Bomb", "Rockets", "1 Box", 300),
  P("2 Sound Rocket", "Rockets", "1 Box", 540),
  P("Musical Rocket", "Rockets", "1 Box", 550),
  P("25 Shot Crackling Riders", "Rockets", "1 Box", 950),
  P("50 Shot Crackling Riders", "Rockets", "1 Box", 1900),
  // Multicolour Shots
  P("7 Shot (5 Pcs)", "Multicolour Shots", "1 Box", 450),
  P("Flaring Star (Penta) 5 Pcs", "Multicolour Shots", "1 Box", 825),
  P("12 Shot", "Multicolour Shots", "1 Box", 700),
  P("15 Shot MultiColor", "Multicolour Shots", "1 Box", 1150),
  P("15 Shot Full Crackling", "Multicolour Shots", "1 Box", 1300),
  P("30 Shot MultiColor Budget", "Multicolour Shots", "1 Box", 1650),
  P("30 Shot MultiColor", "Multicolour Shots", "1 Box", 2000),
  P("30 Shot Full Crackling", "Multicolour Shots", "1 Box", 2500),
  P("60 Shot MultiColor", "Multicolour Shots", "1 Box", 3750),
  P("120 Shot MultiColor", "Multicolour Shots", "1 Box", 7500),
  P("240 Shot MultiColor Crackling", "Multicolour Shots", "1 Box", 14000),
  P("10x10 Tail Light Shots", "Multicolour Shots", "1 Box", 14750),
  // Fancy Pipes
  P('1" Chota Fancy', "Fancy Pipes", "1 Box", 250),
  P('2" Fancy (Single Pcs)', "Fancy Pipes", "1 Box", 450),
  P('2" Fancy (3 Pcs)', "Fancy Pipes", "1 Box", 1075),
  P('3" Fancy Blue Star', "Fancy Pipes", "1 Box", 1150),
  P('3½" Fancy Blue Star', "Fancy Pipes", "1 Box", 1300),
  P('4" Blue Star (2 Pcs)', "Fancy Pipes", "1 Box", 4000),
  P('4½" 7 Step Blue Star', "Fancy Pipes", "1 Box", 2600),
  P('4½" Cool Rain Blue Star', "Fancy Pipes", "1 Box", 1950),
  P('5" Fancy Beema', "Fancy Pipes", "1 Box", 3400),
  P('5" Mercury (2 Pcs)', "Fancy Pipes", "1 Box", 7500),
  // Pencil Celebration
  P("Selfi Stick", "Pencil Celebration", "1 Box", 950),
  P("Sivakasi Special", "Pencil Celebration", "1 Box", 900),
  P("Gun Squad", "Pencil Celebration", "1 Box", 1050),
  P("Sword Knife", "Pencil Celebration", "1 Box", 750),
  P("Water Falls Pencil", "Pencil Celebration", "1 Box", 950),
  // Kids Special
  P("Photo Flash", "Kids Special", "1 Box", 350),
  P("Digital Wala (Pop it)", "Kids Special", "1 Box", 750),
  P("Tin Fountain (1 Pcs)", "Kids Special", "1 Box", 450),
  P("Water Falls Tin", "Kids Special", "1 Box", 900),
  P("Tri Color Fountain", "Kids Special", "1 Box", 1150),
  P("Tik Tok", "Kids Special", "1 Box", 175),
  P("Drone", "Kids Special", "1 Box", 650),
  P("Pambaram", "Kids Special", "1 Box", 575),
  P("Butterfly", "Kids Special", "1 Box", 475),
  P("Lollypop", "Kids Special", "1 Box", 1100),
  P("Money Bank", "Kids Special", "1 Box", 775),
  P("4x4 Wheel", "Kids Special", "1 Box", 800),
  P("90 Watts", "Kids Special", "1 Box", 725),
  P("Madurai Malli", "Kids Special", "1 Box", 925),
  P("Fire Egg", "Kids Special", "1 Box", 600),
  P("Bat & Ball", "Kids Special", "1 Box", 1150),
  P("Rainbow Smoke", "Kids Special", "1 Box", 900),
  P("Planet Wheel", "Kids Special", "1 Box", 950),
  P("Whistling Dixie", "Kids Special", "1 Box", 650),
  P("Disco Wheel", "Kids Special", "1 Box", 600),
  P("Disco Shower", "Kids Special", "1 Box", 500),
  P("Small Peacock", "Kids Special", "1 Box", 675),
  P("Bada Peacock", "Kids Special", "1 Box", 2000),
  P("Mini Siran", "Kids Special", "1 Box", 750),
  P("Mega Siran", "Kids Special", "1 Box", 875),
  P("Helicopter", "Kids Special", "1 Box", 375),
  P("Gold Spinner", "Kids Special", "1 Box", 1250),
  // Color Matches
  P("Super Deluxe", "Color Matches", "1 Box", 500),
  P("Queen Box", "Color Matches", "1 Box", 900),
  P("Big Boss", "Color Matches", "1 Box", 1175),
  P("Ring Cap", "Color Matches", "1 Box", 75),
  P("Roll Cap", "Color Matches", "1 Box", 75),
  // Sparklers
  P("7 Cm Sparklers Electric", "Sparklers", "1 Box", 50),
  P("7 Cm Sparklers Color", "Sparklers", "1 Box", 60),
  P("7 Cm Sparklers Green", "Sparklers", "1 Box", 70),
  P("7 Cm Sparklers Red", "Sparklers", "1 Box", 80),
  P("10 Cm Sparklers Electric", "Sparklers", "1 Box", 100),
  P("10 Cm Sparklers Color", "Sparklers", "1 Box", 110),
  P("10 Cm Sparklers Green", "Sparklers", "1 Box", 120),
  P("10 Cm Sparklers Red", "Sparklers", "1 Box", 130),
  P("15 Cm Sparklers Electric", "Sparklers", "1 Box", 225),
  P("15 Cm Sparklers Color", "Sparklers", "1 Box", 240),
  P("15 Cm Sparklers Green", "Sparklers", "1 Box", 265),
  P("15 Cm Sparklers Red", "Sparklers", "1 Box", 280),
  P("30 Cm Sparklers Electric", "Sparklers", "1 Box", 300),
  P("30 Cm Sparklers Color", "Sparklers", "1 Box", 315),
  P("50 Cm Sparklers Electric", "Sparklers", "1 Box", 780),
  P("50 Cm Sparklers Color", "Sparklers", "1 Box", 920),
  P("50 Cm Sparklers 5 in One", "Sparklers", "1 Box", 1050),
  P("Rotating Sparklers", "Sparklers", "1 Box", 1100),
  P("Love Sparklers", "Sparklers", "1 Box", 300),
  P("Heartin Sparklers", "Sparklers", "1 Box", 300),
  // Gift Boxes
  P("20 Items Chutties Box", "Gift Boxes", "1 Box", 2160, 17),
  P("25 Items Silver Box", "Gift Boxes", "1 Box", 2410),
  P("30 Items Golden Box", "Gift Boxes", "1 Box", 2625),
  P("35 Items Diamond Box", "Gift Boxes", "1 Box", 3300),
  P("40 Items Platinum Box", "Gift Boxes", "1 Box", 4275),
  P("45 Items Royal Box", "Gift Boxes", "1 Box", 5325),
  P("50 Items Family Box", "Gift Boxes", "1 Box", 6375),
  P("60 Items VIP Box", "Gift Boxes", "1 Box", 10125),
  // New Arrivals
  P("Race Car", "New Arrivals", "1 Box", 2000),
  P("Phone", "New Arrivals", "1 Box", 1250),
  P("Glitter", "New Arrivals", "1 Box", 1200),
  P("Pop Mix", "New Arrivals", "1 Box", 650),
  P("Hanuman Gadha", "New Arrivals", "1 Box", 1050),
  P("Cylinder Bomb", "New Arrivals", "1 Box", 1300),
];
